### ISSUE TITLE
web console not found

### ISSUE THREAD

**Issue by henjue** [vletroye/SynoPackages#1]
dsm version 6.2-23511

![1](https://user-images.githubusercontent.com/1314740/35675182-13d4ff90-0782-11e8-93b8-bf084d9a395f.png)

**Comment by vletroye** [comment]
CTRL-F5 in the browser and retry...
Also, open the Console page (F12 > Console) before clicking on Web console, so one can see more details

![image](https://user-images.githubusercontent.com/9768028/35704227-1235eb46-079f-11e8-8d92-7623b1a5d21c.png)

**Comment by vletroye** [comment]
Could ou also possibly try with the version from my [SPK server ](http://olympe.letroye.be/sspks/?arch=all#)

And once the Web Console opened, go to the Package Center, open the package and click on "View Log" to show if the router.cgi has been properly executed

![image](https://user-images.githubusercontent.com/9768028/35704889-2800c5ca-07a1-11e8-9b02-dbc9459cd2ee.png)

**Comment by henjue** [comment]
@vletroye  
I used the VirtualDSM test!
```
http://nas.j99.io:15000/
admin
111111
```
The problem still exists after the force refresh！
chrome console message:
![1](https://user-images.githubusercontent.com/1314740/35715466-6c0d8cfa-080d-11e8-80d4-26afa2ab6c31.png)

**Comment by henjue** [comment]
The suite depended on php56, but I didn't install php56

**Comment by vletroye** [comment]
Thx a lot for reporting. I did add PHP5.6 as a dependency in the package.
