### ISSUE TITLE
MOD GateOne not compatible with DSM 6

### ISSUE THREAD

**Issue by jgraciar** [vletroye/SynoPackages#2]
Hi, 
I have DSM 6.21-2384 usdate 2 installed.
When I try to install the MODS_GateOne.spk I have this error:
"This packed is not compatible with DiskStation platform or is incompatible with the actual version of DSM"
I'm not able to install this packet.

**Comment by vletroye** [comment]
The package is not compatible with all the models of Synology. It depends on the CPU architecture. I did use the list of supported CPU of the original package. Which model do you have?

**Comment by jgraciar** [comment]
Hi again, 
I have the DS115j model

**Comment by vletroye** [comment]
Your cpu are both 'armada' and the package targets one of these arch="apollolake avoton braswell broadwell broadwellnk bromolow cedarview denverton dockerx64 grantley kvmx64 x86 x86_64"

No idea why such a restriction, I am unfortunately not a expert in GateOne. The best would be to check with a developer maintaining and compiling this code...

**Comment by orioldelos** [comment]
I have a similar issue . I have several Synology DS416, DS416play, DS418 and DS418play, I installed MOD GateOne on a DS416play and although the installation seemed to execute correctly, there is no icon in the DSM console to acces it.

**Comment by orioldelos** [comment]
By the way my DSM version is DSM 6.2.1-23824 Update 6
--




DSM 6.2.1-23824 Update 6
--




DSM 6.2.1-23824 Update 6
--

**Comment by casperse** [comment]
I get this error message
3rdparty/MODS_PackageManager/mvpkg.php might be temporarily down or it may have moved permanently to a new web address.

**Comment by casperse** [comment]
I found this in the config file:
      "url": "/webman/3rdparty/MODS_PackageManager/mvpkg.php",
and the location for this is:
/volume1/@appstore/MODS_PackageManager/ui

so how do I make it work? is it the https?
https://192.168.0.10/webman/3rdparty/MODS_PackageManager/mvpkg.php might be temporarily down or it may have moved permanently to a new web address.

So any way to modify it so the UI will work again?

**Comment by vletroye** [comment]
Casperse, the path is correct, but your URL is weird as it should contain the administration port. 
I.e.: something like: https://192.168.0.10:5001/webman/3rdparty/MODS_PackageManager/mvpkg.php

But to be honest, I don't use https in my LAN, so I didn't test it.
