### ISSUE TITLE
MOD_GateOne package not placing the link to launch GateOne in DSM

### ISSUE THREAD

**Issue by orioldelos** [vletroye/SynoPackages#3]
I have several Synology DS416, DS416play, DS418 and DS418play, I installed MOD GateOne on a DS416play and although the installation seemed to execute correctly, there is no icon in the DSM console to access it.
My DSM version is DSM 6.2.1-23824 Update 6

I can access GateOne fine if I am on the local network by connecting to the GateOne port through HTTP but without the icon in the DSM I can not access it while connected remotely through quickconnect since I can not access that port.

**Comment by vletroye** [comment]
The issue with the icon on DSM 6.2 is reported here: https://github.com/SynoCommunity/spksrc/issues/2340
I didn't see yet a solution posted for that.

Regarding the remote access, you must configure a forward on your Router/NAT.

**Comment by burgerga** [comment]
Per https://github.com/SynoCommunity/spksrc/issues/2340#issuecomment-442606730, did you try to add GateOne privileges to your user? (Control Panel -> Search for 'Privileges', you might need to log out and in again afterward for the icon to appear)
