### ISSUE TITLE
How can I install it?  I am novice

### ISSUE THREAD

**Issue by g2david** [vletroye/SynoPackages#5]
Hi,

how to get start to install it?  with SSH login and download gateone package and run cmd?

**Comment by vletroye** [comment]
In the folder of each Packages, named 'MODS <something> (e.g". MODS AcpiOnLan"), there is a SPK file (e.g. "MODS_AcpiOnLan.spk"). Download it and install it manually via the DSM Package Center.

Or, configure my SPK Server in your the DSM Package Center: https://www.beatificabytes.be/sspks/
